[package]
name = "image_convert_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.8"
glib = "0.19"
image = { version = "0.25", features = ["avif", "jpeg", "webp", "png"] }
rayon = "1.8"
